//
//  MessagesViewController.swift
//  Hive MessagesExtension
//
//  Created by Jude Partovi on 6/6/22.
//

import UIKit
import Messages
import GooglePlaces

#error ("Insert Google Places API Key below, then delete this line")
let googlePlacesAPIKey = ""

class MessagesViewController: MSMessagesAppViewController, InviteViewControllerDelegate, StartEventViewControllerDelegate, UINavigationControllerDelegate {
    
    static var conversation: MSConversation? = nil
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        // This should be in an App Delegate, but there is no App Delegate in an iMessage Extension
        GMSPlacesClient.provideAPIKey(googlePlacesAPIKey)
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        MessagesViewController.conversation = conversation
        
        presentViewController(for: conversation, with: presentationStyle)
        
        // Use this method to configure the extension and restore previously stored state.
    }
    /*
    override func willTransition(to newCollection: UITraitCollection, with coordinator: UIViewControllerTransitionCoordinator) {
        
        presentViewController(for: MessagesViewController.conversation!, with: presentationStyle)
    }
    */
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        print("Did receive")
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }
    
    private func presentViewController(for conversation: MSConversation, with presentationStyle: MSMessagesAppPresentationStyle) {
        
        let controller: UIViewController
        
        if conversation.selectedMessage == nil {
            controller = instantiateStartEventViewController()
        } else {
            guard let messageURL = conversation.selectedMessage?.url else {return}
            guard let urlComponents = NSURLComponents(url: messageURL, resolvingAgainstBaseURL: false), let queryItems = urlComponents.queryItems else {return}
            
            /*
            for queryItem in queryItems {
                guard let value = queryItem.value else { continue }
                        
                print(value)
            }
            */
            
            let value = queryItems[0].value!
            print("Type: " + value)
            
            if value == "invite" {
                controller = instantiateInviteViewController(conversation: conversation)
            } else if value == "vote" {
                controller = instantiateVoteViewController(conversation: conversation)
            } else {
                controller = instantiateStartEventViewController()
                print("Invalid view type")
            }
            
            // BUG: Shows Create Event VC when app is already open and message is clicked
        }
        
        // Remove any existing child controllers.
        for child in children {
            child.willMove(toParent: nil)
            child.view.removeFromSuperview()
            child.removeFromParent()
        }

        // Embed the new controller.
        addChild(controller)
                
        controller.view.frame = view.bounds
        controller.view.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(controller.view)
                
        controller.view.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        controller.view.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
        controller.view.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        controller.view.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
                
        controller.didMove(toParent: self)
    }
    /*
    func instantiateCreateEventViewController() -> UIViewController {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: "NavigationController") as? UINavigationController else { fatalError("Unable to instantiate a NavigationController from the storyboard") }
            
        controller.delegate = self
        
        return controller
    }
    
    func didFinishTask(sender: CreateEventViewController) {
    
    }
     */
    
    func instantiateStartEventViewController() -> UIViewController {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: "NavigationController") as? UINavigationController else { fatalError("Unable to instantiate a NavigationController from the storyboard") }
            
        controller.delegate = self
        
        return controller
    }
    
    func didFinishTask(sender: StartEventViewController) {
    
    }

    
    func instantiateInviteViewController(conversation: MSConversation) -> UIViewController {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: InviteViewController.storyboardID) as? InviteViewController else { fatalError("Unable to instantiate an InviteViewController from the storyboard") }
            
        controller.delegate = self
        controller.myID = conversation.localParticipantIdentifier.uuidString
        controller.mURL = conversation.selectedMessage?.url
        
        return controller
    }
    
    func didFinishTask(sender: InviteViewController) {
    
    }
    
    func instantiateVoteViewController(conversation: MSConversation) -> UIViewController {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: VoteViewController.storyboardID) as? VoteViewController else { fatalError("Unable to instantiate an PollViewController from the storyboard") }
            
        controller.delegate = self
        controller.myID = conversation.localParticipantIdentifier.uuidString
        controller.mURL = conversation.selectedMessage?.url
        
        return controller
    }
    
    func didFinishTask(sender: VoteViewController) {
    
    }
    
}
